### PR TITLE
Clean up Windows, Mac and Linux setup pages

### PR DESCRIPTION
**Pull request by richyvk**
Noticed a lot of the html was not right on these pages causing the setup page to not render properly, so tidied up tags etc.

### CODE REVIEW

**Comment by mkuzak** [comment]
@richyvk Thank you. As you can see in the discussion in issue #17 the rendering is an issue, but actually the content that is rendered is not right. I'll wait for @c-martinez to fix it first

**Comment by richyvk** [comment]
No problem. Should close this then? I was curious about the code. Are these pages (windows.html etc) generated by Jekyll or written directly by us? There were loads of for missing closing tags  - that was the main reason the page whole page wasn't rendering properly.

**Comment by c-martinez** [comment]
@mkuzak -- PR for #17 sent, please check.

@richyvk -- They are generated by us. I think it should render ok now. Sorry, was a bit careless on the previous iteration. Hope it is better now.

**Comment by richyvk** [comment]
@c-martinez Thanks for the explanation :)

**Comment by mkuzak** [comment]
This has been solved through the pull request #28 by @c-martinez . Closing.

**Pull request closed without merging**
