### PR TITLE
Reflect renaming of organization on GitHub

### PR DESCRIPTION
**Pull request by katrinleinweber**
See diff ;-)

However, is this entire repo a duplicate of [LibraryCarpentry/lc-python-intro](https://github.com/LibraryCarpentry/lc-python-intro)? cc @weaverbel

If yes, please [archive](https://help.github.com/articles/archiving-repositories/) one of them quickly.

### CODE REVIEW

**Comment by jt14den** [comment]
Thanks @katrinleinweber ! I forgot about this lesson. It predates and is a different approach from the other one that was created in the 2017 sprint (it includes pandas and matplotlilb for example). I'm teaching a LC next month and the organizers want Python, but with data applications. I think we will use this as a base and add a couple of episodes using the circ and headcount data they shared. We can submit the work we come up with as a PR.

**Comment by weaverbel** [comment]
Hi @katrinleinweber and @jt14den I moved this earlier lesson across from `data-lessons` as that area needs to be cleared out now we have migrated the repos to the LC organisation. This was the original python lesson on which @c-martinez and others worked and then @richyvk decided to create a more basic one. So now we have two ! The one @richyvk built was worked on during the 2017 sprint but Richard is now flat out with a new job and hasn't had much time for work on the lesson. It would be good for all interested pythonistas to figure out what we need to include and decide on a lesson strategy at some stage - maybe we could have a one-day Plan-and-Do-a-Thon for the python lesson as there is also a great lesson on beautiful soup for webscraping that we could incorporate.

**Comment by libcce** [comment]
@weaverbel @jt14den @katrinleinweber reconsidering the Python lessons will most likely be one of the first items the CAC at least discusses. First meeting is Aug 8. As part of the IMLS grant, we definitely need to have targeted do-a-thons to publish the first versions of the lessons to Zenodo. I was hoping to bring this up in the CAC.

**Comment by jt14den** [comment]
@katrinleinweber @libcce @weaverbel  I'll be incubating this lesson with a soon to be trained instructor that addresses one of our host's wishes for a workshop next month. We will be following our current instructions for lesson development found on our website. We will gather feedback and suggestions for further development. Wish us luck! :)

**Comment by katrinleinweber** [comment]
OK, thanks for the info. We should consider a rename of either this repo then (`lc-python-data`, for example to distinguis it better from `..-intro`), or even dropping both `lc` and `library` from the repo names entirely, now that they are no longer under `data-lessons`.

**Comment by jezcope** [comment]
@jt14den @katrinleinweber I taught this lesson recently and have some reflections that I've been meaning to get round to writing up and contributing. I still intend to do that but I'm not sure when that will be!

In a nutshell: I would support a major overhaul to use text manipulation rather than mathematical operations as the building blocks. The simple arithmetic used is well within the grasp of our learners, but nonetheless can be off-putting for those who have chosen a non-scientific career and also carries more cognitive load when compared to text manipulation.

**Pull request merged**
